### ISSUE TITLE
Alle datasets met meldingen: Geeft altijd "Sterrenwacht"

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#1]
Hier verschijnt een melding over een dataset "sterrenwachten" die een structuurwijziging ondergaan zou hebben. De dataset is er echter niet meer en ook de bron is er niet. Kan deze dataset of melding niet verwijderen.

**Comment by copierrj** [comment]
connects to IDgis/geo-publisher#388

**Comment by andreweijmer** [comment]
Is niet meer te zien. lijkt nu goed te gaan
