### ISSUE TITLE
Servicebeheer / subscherm lagen / publiceren

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#10]
indien publiceren uitgevinkt staat en de laag wordt aan een service toegevoegd dan is deze toch direct in geoserver gepubliceerd. De laag staat in de publisher echter nog steeds  uitgevinkt.

**Comment by HermanAssink** [comment]
Het idee van het Publiceren vinkje was dat je in staging een laag in een service kan opvoeren zonder dat die laag wordt doorgezet naar de publicatieomgeving als Publiceren=nee. Bij nader inzien is dit misschien verwarrend. Het doorzetten naar publicatieomgeving, het feitelijke publiceren, moet nog worden gebouwd. Voorstel is om dit te doen door bij een service op Publiceren knop/actie te klikken. 
Wat betreft het Publiceren vinkje is ons voorstel om dit overal weg te halen. Dit betekent dat als een service gepubliceerd wordt alle lagen in die service meegaan naar de publicatieomgeving.

**Comment by andreweijmer** [comment]
Ik heb hier nog eens naar gekeken. Ik denk dat deze optie toch gehandhaafd moet blijven om de volgende reden. Een laag wordt pas gepubliceerd als de beheerder daartoe opdracht geeft (publiceren=ja). Als je de service als geheel publiceert is dat niet meer mogelijk.

**Comment by HermanAssink** [comment]
OK, we hebben afgesproken dat de workflow voor publiceren blijft zoals eerder gedacht: Het vinkje geeft aan of een laag/groep mee moet naar de productie-/publicatieomgeving en er komt een aparte knop bij iedere service waarmee deze overgezet kan worden naar de productie-/publicatieomgeving.

**Comment by HermanAssink** [comment]
Bij nader inzien blijkt de indicatie "wel/niet publiceren" bij lagen en groepen niet nodig omdat het mogelijk is lagen en groepen te maken zonder die in een te publiceren service op te nemen. Om zo'n laag/groep toch te kunnen bekijken in staging kan een aparte service worden gemaakt die niet gepubliceerd wordt. Voorgaande is met André Weijmer besproken en door hem akkoord bevonden.

**Comment by andreweijmer** [comment]
Naar aanleiding van het voorgaande zou de indicatietekst "gepubliceerd/niet gepubliceerd" weggehaald moeten worden bij lagen en groepen omdat dit bij de service vermeld staat. 
of
Wel vermelden bij de laag of groep indien de laag of groep in een service zit die gepubliceerd is.

**Comment by andreweijmer** [comment]
Prima
