### ISSUE TITLE
Servicebeheer / lagen / subscherm lagen / knop preview: GetFeatureInfo fout

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#11]
preview wordt correct getoond. Identify levert, bij alle lagen, de volgende melding op: java.lang.IllegalArgumentException: Null charset name Null charset name

**Comment by HermanAssink** [comment]
Gereproduceerd. Ook op andere plaatsen waar GeoServer xml moet genereren treedt deze fout op

**Comment by copierrj** [comment]
oorzaak:  encoding bij workspace ontbreekt

**Comment by PeterAukeNicolaij** [comment]
werkt nu prima
