### ISSUE TITLE
Lagen / groepen worden soms dubbel aangemaakt in GeoServer. Geeft dit schaalbaarheidsproblemen?

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#12]
na publiceren is in geoserver, bij lagen, te zien dat de twee lagen die in de grouplayer zitten nogmaals als laag opgenomen zijn. Wat is de reden hiervan?

**Comment by HermanAssink** [comment]
Als een laag (en groep) in meerdere services voorkomt dan wordt die laag/groep in iedere omgeving binnen GS opgevoerd. Op die manier wordt het mogelijk lagen en groepen eenmalig te definiëren en toch in meerdere services te gebruiken.

**Comment by andreweijmer** [comment]
Ok, dat snap ik. Je krijgt dan wel heel veel lagen. Zal Geoserver dit aankunnen.

**Comment by HermanAssink** [comment]
We zullen moeten testen of de extra lagen teveel van GeoServer vragen. Van welke lagen verwacht jij dat die veel in meerdere services gebruikt gaan worden?

**Comment by andreweijmer** [comment]
Het komt veel voor dat bij gecombineerde kaarten kaartlagen zoals gemeentegrenzen, provinciegrenzen, stedelijkgebied e.d. hier aan toegevoegd worden.

**Comment by HermanAssink** [comment]
We verwachten geen performance probleem in GeoServer agv van het vaker aanmaken van dezelfde laag. GeoServer heeft niet veel resources nodig voor de configuratie.

**Comment by andreweijmer** [comment]
ok
