### ISSUE TITLE
Servicebeheer / groepen / subscherm maak een nieuwe groep en bewerk groep / voeg groep toe

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#13]
indien een service gebruikt wordt (bijv. groepen) dan kun je geen groep toevoegen die al gebruikt is. Je moet dus voor elke groep een nieuwe service aanmaken. Hier zijn wij niet blij mee. Je kan hierdoor gigantisch veel services krijgen.

**Comment by HermanAssink** [comment]
In de GPO beheermodule is een groep een lijst met lagen en/of groepen. Een groep kun je opnemen in één of meer services en/of in andere groepen. Je hoeft dus niet voor iedere groep een nieuwe service te maken. Hoe zou je groepen en services willen gebruiken zodat dat tot "gigantisch veel services" leidt?

**Comment by andreweijmer** [comment]
Wij hebben geprobeerd een service "Groepen" aan te maken om daarin alle groepen in onder te brengen. Als wij daar nu een group die al bestaat onder brengen in een nieuwe groep en deze in de service groepen plaatsen dan mag dit niet omdat deze groep al gebruikt is.

**Comment by HermanAssink** [comment]
Waarom zou je alle groepen in één service willen zetten? Groepen kun je vrij toekennen aan iedere willekeurige service

**Comment by andreweijmer** [comment]
Om het overzicht te behouden. Daarnaast treedt hetzelfde probleem op dat een groep die al in een groep voorkomt niet twee keer in 1 service geplaatst mag worden.

**Comment by HermanAssink** [comment]
Telefonisch werd duidelijk dat het wenselijk is om een bepaalde laag vaker in een service op te nemen, namelijk als die laag in verschillende groepen zit waarbij deze groepen in dezelfde service nodig zijn, bijv. gemeentegrenzen die in combinatie met andere themalagen getekend moeten worden. Afgesproken is dat we in een later stadium hierop terugkomen.

**Comment by HermanAssink** [comment]
Het is nu mogelijk om dezelfde laag vaker in dezelfde service, eventueel onder verschillende groepen, voor te laten komen.

**Comment by andreweijmer** [comment]
Werkt correct.
