### ISSUE TITLE
Algemene opmerkingen

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#14]
1. Verwijderknoppen binnen invoervensters gelijk maken qua kleur (wit moet oranje worden)
2. Wij missen, onder algemeen beheer, de getcapabilities van de diverse soorten services.
   3.Verwerking van gegevens gaat vrij traag (publiceren) Hierdoor kun je niet snel werken.
3. Geoserver vrij traag.

**Comment by HermanAssink** [comment]
opm 1 zie #15 
opm 2, zie #16
opm 3, zie #17 
opm 4, zie #18
