### ISSUE TITLE
Verwijderknoppen binnen invoervensters gelijk maken qua kleur (wit moet oranje worden)

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geo-publisher-test#15]

**Comment by HermanAssink** [comment]
OK, verwijderknoppen moeten in invoervensters (aanmaken/bewerken) dezelfde opmaak krijgen als in de lijsten, dus oranje.

**Comment by andreweijmer** [comment]
Zie nog steeds witte knoppen i.p.v. oranje

**Comment by andreweijmer** [comment]
Is nu ok
