### ISSUE TITLE
Geoserver vrij traag

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geo-publisher-test#18]

**Comment by HermanAssink** [comment]
Wordt hier gedoeld op de GeoServer admin of op het tekenen? Moet we misschien ook versie 2.5.2 van GeoServer gebruiken? Op dit moment wordt versie 2.6.1. gebruikt.

**Comment by andreweijmer** [comment]
De geoserver admin wordt hiermee bedoeld. De preview wordt snel getoond.

**Comment by HermanAssink** [comment]
Onze indruk is dat de GeoServer admin in het algemeen niet snel is. Is de GeoServer admin op de server van Overijssel sneller?

**Comment by andreweijmer** [comment]
Ja
