### ISSUE TITLE
Bij categorie zowel naam als technische aanduiding

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geo-publisher-test#19]
In het blok om op categorieën te filteren staat nu alleen de naam. De wens was er om daar ook de technische aanduiding (id) zichtbaar te maken. Welke manier heeft hier de voorkeur voor? Eén manier is om de technische naam in een wolkje te tonen wanneer de muis over de naam staat.

**Comment by PeterAukeNicolaij** [comment]
Prima om de technische naam in een wolkje te tonen bij mouseover.

**Comment by andreweijmer** [comment]
lijkt mij goed nu
