### ISSUE TITLE
Graag testdata voor rasterdata

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geo-publisher-test#21]
We willen graag testdata voor de rasterbestanden. Dit betekent dat er een aparte map/folder met metadata voor rasterdata moet zijn. In de metadata wordt in de alternateTitle het volledige pad naar het geoTiff bestand opgenomen. De provider component op de server van Overijssel moet met dit pad het geoTiff bestand kunnen ophalen.
Wanneer kun je deze testdata leveren?

**Comment by andreweijmer** [comment]
Metadata voor rasters willen we niet in een andere map plaatsen. Dat zou inhouden dat wij dubbel beheer qua metadata krijgen. In de tag "ruimtelijk schema" staat vermeld of het een raster- of een vectorbestand is. Het pad naar de geotiff kunnen wij in de alternate Ttile plaatsen en moet absoluut zijn configurabel.

**Comment by andreweijmer** [comment]
n.a.v. mailwisseling. Wij gaan twee aparte folders aanmaken. 1 voor vector- en 1 voor rasterdata.
Wij verwachten dit as. woensdag te kunnen aanbieden.

**Comment by PeterAukeNicolaij** [comment]
Naast Raster en Vector datasets hebben we een aantal tabellen, voorzien van metadata, om te koppelen (join) aan de geometrie. Hoe gaan we hier mee om?
