### ISSUE TITLE
Ondersteuning meerdere databases 

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geo-publisher-test#22]
De wens is om met 1 map met metadata naar meerdere databases te kunnen verwijzen. Vraag daarbij is hoe in de metadata naar de betreffende database verwezen wordt. Bij voorkeur dit kenmerk niet toevoegen aan alternateTitle, maar een passend ISO element hiervoor gebruiken. Overijssel zoekt uit hoe dit het beste opgelost kan worden.

**Comment by andreweijmer** [comment]
De verwijzing, in de metadata, naar de database is bij de meeste datasets al ingevuld in de onderstaande tag (de naam achter LOCAL=). Voor ons houd dat in dat wij deze url bij alle datasets moeten invullen)

<CI_OnlineResource>
              <linkage>
                <URL>Service=sde:oracle11g:/;LOCAL=GISBASIP; User=b4; Version=SDE.DEFAULT</URL>
              </linkage>

**Comment by copierrj** [comment]
mogelijk dmv het configureren van meerdere provider instanties

**Comment by andreweijmer** [comment]
Werkt correct i.g.v RASTER. Hiervoor is een nieuwe WAF aangemaakt waaruit de rasterdata gelezen wordt.
Houdt dit ook in dat een nieuwe WAF aangemaakt moet worden voor bijvoorbeeld een database KADP?

**Comment by HermanAssink** [comment]
Inderdaad, per database moet er een WAF met metadata zijn. Reinder kan hiervoor een extra instantie van de provider configureren. Deze extra instantie moet ook bij de harvester (onze kant) bekend zijn zodat de koppeling gelegd kan worden.

**Comment by andreweijmer** [comment]
Ok. is duidelijk
