### ISSUE TITLE
Valideren van stijlen zou melding moeten geven en niet terugkeren naar scherm met alle stijlen

### ISSUE THREAD

**Issue by PeterAukeNicolaij** [IDgis/geo-publisher-test#23]
Graag conform GeoServer een melding tonen of er validation errors zijn en bij de desbetreffende stijl blijven zonder terug te keren naar het overzichtsscherm met stijlen.

**Comment by HermanAssink** [comment]
OK, gaan we doen. Reijer heeft trouwens in de GeoServer API geen functie gevonden waarmee we die validatie aan GeoServer kunnen uitbesteden.

**Comment by andreweijmer** [comment]
Geeft nog geen melding bij valideren.

**Comment by PeterAukeNicolaij** [comment]
Bij het opslaan van een nieuwe stijl krijg ik de melding dat de publicatieservice niet beschikbaar is.
![fout](https://cloud.githubusercontent.com/assets/9866079/6820792/8427eace-d2d2-11e4-8313-5b0f70475d8a.PNG)

**Comment by HermanAssink** [comment]
Welke SLD gaf deze foutmelding en hoe groot was de SLD precies? SLD's groter dan 100kB zijn nog een probleem.
Overigens, deze issue is nog "in progress" en niet "readyfortest".

**Comment by PeterAukeNicolaij** [comment]
Het gaat om:
avo_leegstand_buurt_kantoren_perc
deze is 6 kB. Ik wacht met verder testen van die issue.

**Comment by erikorbons** [comment]
Stijlen worden gevalideerd tegen het SLD schema bij opslaan, tevens voert "valideer" knop nu een ad-hoc validatie uit zonder het formulier te verlaten (of op te slaan). 

Validatiefouten zijn waar mogelijk voorzien van een regelnummer.

Deze functionaliteit is beschikbaar in de eerstvolgende versie (0.7.0).

**Comment by andreweijmer** [comment]
Werkt correct. Wel vragen wij ons af waarom hier nog het "type stijl" aangegeven moet worden. De stijl wordt toch aan de laag gekoppeld o.b.v. de naam?

**Comment by HermanAssink** [comment]
Het type wordt inderdaad nu niet gebruikt door de programmatuur. Het is aan de gebruiker om het type in overeenstemming met de Symbolizer in te vullen. Eventueel zou het type gebruikt kunnen worden als filter bij de lijst van stijlen.

**Comment by andreweijmer** [comment]
Ok, maar dan moet het wel mogelijk zijn om daar ook daadwerkelijk op te filteren. Anders weghalen.

**Comment by HermanAssink** [comment]
Wordt opgevolgd door #46
