### ISSUE TITLE
Property namen in SLD omzetten naar lower case

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geo-publisher-test#26]
In verband met het gebruik van PostgreSQL worden kolomnamen bij het importeren overgezet naar lower case. Dit heeft als consequentie dat de property namen in SLD ook lower case moeten zijn. IDgis  past de programmatuur voor de configuratie aan zodat de property namen in SLD automatisch naar lower case worden omgezet.

**Comment by andreweijmer** [comment]
werkt correct
