### ISSUE TITLE
Groepen / groep aanpassen : Verschillende slds worden niet toegepast

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#28]
Als ik een groep aanmaak en daarin bijv. twee keer dezelfde laag inlaadt die verschillende sld's gebruiken en ik sla deze op en ga vervolgens deze groep weer bekijken dan hebben de twee lagen dezelfde sld gekoppeld.

**Comment by HermanAssink** [comment]
Gereproduceerd, geeconstateerd in de admin André, hoe urgent is dit probleem?

**Comment by andreweijmer** [comment]
Niet direct. Ook voor oplevering

**Comment by robstek** [comment]
constatering: 
Opslaan naar database tabel gaat goed. 
Het gaat mis bij teruglezen uit de database.

**Comment by copierrj** [comment]
locatie in code: ServiceManager

**Comment by andreweijmer** [comment]
Als ik een groep aanmaak en daarin bijv. twee keer dezelfde laag (bijv. gemeentegrenzen in de groep "Groep_test") inlaadt die verschillende sld's gebruiken en ik sla deze op en ga vervolgens deze groep weer bekijken dan hebben de twee lagen dezelfde sld gekoppeld.

**Comment by andreweijmer** [comment]
Werkt nog steeds niet correct.

**Comment by HermanAssink** [comment]
Klopt, dit punt komt mee in de volgende release.

**Comment by andreweijmer** [comment]
Werkt nog niet.

**Comment by andreweijmer** [comment]
werkt correct
