### ISSUE TITLE
Lagen / lagen aanpassen : zit in de groep, wordt niet getoond

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#29]
Als ik een laag in een groep heb geplaatst moet hier weergegeven worden dat hij in een groep zit.

zie Laag Aardgastransportleidingen aanpassen

**Comment by HermanAssink** [comment]
Het weergeven van de groepen/services (parents) waarin een laag zit, is nog niet gebouwd. Idem voor groepen in groepen.
André, welke prioriiteit moet dit hebben?

**Comment by andreweijmer** [comment]
Hoeft niet direct. Groepen gaan we pas aanmaken als alles opgeleverd is. Dus wel graag nog voor oplevering.

**Comment by andreweijmer** [comment]
is prima
