### ISSUE TITLE
Databeheer / datasets / knop bewerken: Meldingcode @6lfji4ld4

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#3]
Bij dataset aanpassen, kolommen: na uitvinken kolom komt de melding dat publicatieservice niet beschikbaar is. Meldingcode @6lfji4ld4. kolom staat echter wel uitgevinkt. Idem bij toepassen filter.

**Comment by HermanAssink** [comment]
Gereproduceerd

**Comment by copierrj** [comment]
verholpen in IDgis/geo-publisher@bd98423ba5bd891f4d92095ce84bf750fc1c2a31

**Comment by andreweijmer** [comment]
werkt nu correct
