### ISSUE TITLE
Categorieën : lagen die niet bestaan

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#31]
Vraag: hoe kan het dat ik categorieën zie die niet bestaan? 

Bijvoorbeeld de onderstaande rasterbestanden:
- 2013_totaalmozaiek_overijssel_10cm
- 2013_totaalmozaiek_overijssel_25cm
- overijssel_totaal_75

en uit andere schema's:
- gemeenten
- h2o waterprojecten
- o2 omgevingsvisie
- overijssel_totaal_75

**Comment by HermanAssink** [comment]
Vermoedelijk werden deze categorieën genoemd in een eerdere versie van de metadata. De lijst met categorieën wordt bij een lege database gevuld a.d.h.v. de gegevens die de PublisherProvider levert. De PublisherProvider leidt dat weer af uit de metadata. Omdat de database niet bij iedere nieuwe versie v.d. programmatuur is leeg gemaakt, zijn de vervallen categorieën blijven staan.

**Comment by andreweijmer** [comment]
Vervallen categorieën moeten toch automatisch opgeruimd worden? Straks in productie wordt de database toch ook niet steeds opgeschoond.

**Comment by andreweijmer** [comment]
werkt correct.
