### ISSUE TITLE
Getcapabilities overige services

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#32]
Waar vindt ik straks de overige getcapabilities (WMTS, TMS....)?

**Comment by HermanAssink** [comment]
De capabilities url voor WMTS en TMS (geowebcache) is voor alle services gelijk. Zullen we die links bovenaan de lijst met services zetten?

**Comment by andreweijmer** [comment]
is prima

**Comment by andreweijmer** [comment]
Is prima,
