### ISSUE TITLE
Brongegevens/met fouten: Gegevens blijven staan

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#34]
Als ik bij brongegevens de fouten bekijk zie ik (meta)gegevens staan waarvan de dataset en metadata al verwijdert zijn. het lijkt erop dat de lijst niet bijgewerkt wordt. (bijvoorbeeld:puntenbestand met huisnummers straatnamen e.d. (LKI)).

**Comment by HermanAssink** [comment]
connects to IDgis/geo-publisher#497

**Comment by andreweijmer** [comment]
Lijkt nu goed te gaan.
