### ISSUE TITLE
Lagen; stijlweergave loopt uit scherm

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#36]
Bij veel SLD's die aan de laag gekoppeld zijn loopt de balk uit het scherm. Hier zou een linebreak toegepast moeten worden. (Zie laag "gemeentegrenzen")

**Comment by PeterAukeNicolaij** [comment]
Ik zie geen verschil tov vorige versie. Kunnen de stijlen niet net als de trefwoorden onder elkaar geplaatst worden (en alfabetisch)?
![stijlen](https://cloud.githubusercontent.com/assets/9866079/7019863/83f09c6c-dd14-11e4-9b2e-3c7868c00e05.PNG)

**Comment by andreweijmer** [comment]
Prima, werkt nu goed
