### ISSUE TITLE
Ook op andere plaatsen dan <ogc:PropertyName> property namen omzetten naar kleine letters

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geo-publisher-test#38]
In bijv. ExternalGraphic/xlink komen bij gebruik van de Chart extensie property namen voor in de url

**Comment by copierrj** [comment]
Het is gelukt om PostGIS + GeoServer met hoofdletters te laten werken

**Comment by andreweijmer** [comment]
Klasse, werkt nu goed
