### ISSUE TITLE
Beveiligde services

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#39]
Hoe gaan we met beveiligde services om?

Afgesproken is dat een mapservice "Beveiligd" aangemaakt wordt. Lagen die voorzien zijn van Metadata en waar een veiligheidsrestrictie op van toepassing is moeten aan deze mapservice toegevoegd worden.

Voorwaarde is dat bij bronbestanden en datasets duidelijk gemaakt moet worden dat het om een beveiligde kaartlaag gaat d.m.v. een symbool of tekst  in rood. Daarnaast mag een laag die restricties heeft niet aan een van de andere services toegevoegd worden. Het systeem moet dan een melding afgeven.

Als een groep een beveiligde laag bevat en ook openbare lagen dan mag de groep alleen in de beveiligde omgeving geplaatst worden.

**Comment by HermanAssink** [comment]
Bij bronbestanden en datasets zal een indicatie worden gemaakt waaruit blijkt of het om beveiligde data gaat. 

Voorstel van IDgis is om bij het publiceren van een service te controleren dat er geen beveiligde data in een niet beveiligde omgeving (publiek of gegarandeerd) worden gepubliceerd. 

Om bij het toevoegen van beveiligde data aan een service (of groep) te controleren of betreffende service(s) beveiligd zijn, is duidelijk meer ontwikkelwerk. Bovendien is al of niet beveiligd zijn niet een eigenschap van de service, maar van de omgeving waarop de service gepubliceerd wordt.

**Comment by erikorbons** [comment]
Is geïmplementeerd, komt mee in de eerstvolgende release (0.8.0).

**Comment by andreweijmer** [comment]
Een laag die een restrictie "vertrouwelijk" heeft kan en mag niet in een andere service dan Beveiligd geplaatst worden. Ik kan nu een vertrouwelijk laag in elke willekeurige service zetten zonder dat een melding verschijnt. Zie eerste melding. Daarin wordt aangegeven dat alle vertrouwelijke lagen in de "beveiligd" map komt.

Het publiceren van de service dwingt dit wel correct af en werkt ook correct.

**Comment by andreweijmer** [comment]
Bij het publiceren van de service waarin een beveiligde laag is opgenomen dwingt af dat de gehele service naar de beveiligde omgeving moet. Het systeem zou moeten reageren op het moment dat een beveiligde laag in een van de andere services (dan beveiligd) geplaatst gaat worden.

**Comment by HermanAssink** [comment]
Dit komt toch op hetzelfde neer, namelijk dat een service met een beveiligde laag alleen in een beveiligde omgeving gepubliceerd mag worden?

**Comment by andreweijmer** [comment]
Akkoord
