### ISSUE TITLE
Importeren raster dataset AHN25 lukt niet

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#41]
De raster dataset AHN25 "Actueel Hoogtebestand Nederland 1, grid 25x25 m" geeft bij import de volgende melding:  Fout bij importeren: 08-04-2015 08:22:56.

Vervolgens werkt de publicatie-omgeving niet meer. Na ongeveer 10 minuten is de publicatieomgeving weer te gebruiken.

**Comment by andreweijmer** [comment]
Importeren lijkt gelukt.De voortgangsindicator blijft actief. Niet alleen in het scherm datasets maar ook op het dashboard. Daarna laag aangemaakt en in service geplaatst. controle uitgevoerd (preview). Blijkt dat laag in geoserver niet is aangemaakt.

**Comment by HermanAssink** [comment]
Kun je het actief blijven van de voortgangsindicator reproduceren? Zo ja, hoe? Wij hebben dit namelijk niet geconstateerd.

**Comment by andreweijmer** [comment]
Ik heb de pubomgeving in een andere browser opgestart (chrome) en daarin zie ik de voortgangsindicator niet meer. Blijkt dus een IE-issue te zijn (caching?). In probeer nu in Chrome een andere rasterdataset te importeren. Hierbij is geen indicator te zien. 

Het lijkt erop dat het gedrag in IE en in Chrome verschilt.

**Comment by copierrj** [comment]
Het issue mbt de voortgangsindicator is een nieuw probleem: #53
