### ISSUE TITLE
Tiling: kan het aantal levels niet instellen

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#42]
Volgens mij was afgesproken dat ook het aantal levels instelbaar zou zijn. Ik kan hier nu geen instellingen voor configureren. Nu wordt, standaard,  21 levels getiled.

**Comment by HermanAssink** [comment]
Ons idee is om bij het overzetten naar de publicatieomgeving de gridset (NL) en het aantal tile levels op een vaste waarde, bijv. 11, in te stellen. In de UI is het dan niet nodig hiervoor een waarde op te geven. Mee eens?

**Comment by andreweijmer** [comment]
Tiling werkt. Als ik echter de tiling bekijk dan valt op dat na 7 stappen geen beeld meer getoond wordt. De tiles worden niet automatisch gegenereerd vanaf dat niveau (zie bodemkaart met veenkartering).

https://acc-staging-services.geodataoverijssel.nl/geoserver/gwc/demo/OV_B4:B4_Bodemkaart_met_veenkartering?gridSet=urn:ogc:def:wkss:OGC:1.0:NLDEPSG28992Scale&format=image/png 

Als dit begrensd is tot dit aantal levels dan zal de functionaliteit aangepast moeten worden. De kadastrale percelen moeten getoond kunnen worden tot een dieper niveau.

**Comment by copierrj** [comment]
De geo-publisher configureert een tiling laag met een maximum cached level van 11. Dit wordt correct doorgezet naar GeoServer maar leidt tot een crash bij het opvragen van een niet gecachte tile.

**Comment by andreweijmer** [comment]
Werkt goed
