### ISSUE TITLE
Vraag 

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#44]
Als bij brongegevens de fouten tonen wordt nu, bij veel lagen, weergegeven dat de revisiedatum ontbreekt (Fout bij het verwerken van de metadata: revisiedatum niet gevonden).

Is dit een probleem als de acceptatieomgeving overgezet wordt naar de productie-omgeving voor de al ingevoerde datasets in deze productie-omgeving?

**Comment by HermanAssink** [comment]
Nee, de data (metadata, data en serviceconfiguratie) van acceptatie- en productieomgeving zijn volledig gescheiden. Trouwens, het kan zijn dat de foutmeldingen op acceptatie zijn ontstaan door een test die Reijer heeft uitgevoerd.

**Comment by andreweijmer** [comment]
ok
