### ISSUE TITLE
vraag

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#45]
Bij de lagen zijn de kolomnamen nu veranderd van onderkast naar hoofdletters.

In de productie-omgeving zijn wij nu aan het invoeren. Daar staan de kolomnamen van de lagen echter nog in onderkast. Houdt dit in dat wij in de productieomgeving alles opnieuw moeten doen?

**Comment by HermanAssink** [comment]
Nee, alles hoeft niet overnieuw. Wel is het nodig om in de lijst met datasets bij iedere dataset de knop "Verversen uit brondata" een keer te klikken zodat de tabel opnieuw wordt aangemaakt met hoofdletters voor de kolomnamen.

**Comment by andreweijmer** [comment]
ok
