### ISSUE TITLE
aanpassen stijl van laag in service kan niet

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#49]
Ik probeer in een service OV_B1 de stijl van een laag gemeentegrenzen aan te passen. Dit lukt niet.

**Comment by andreweijmer** [comment]
werkt correct

**Comment by HermanAssink** [comment]
Het kan wel met de admin geconfigureerd worden maar wordt nog niet goed doorgezet naar GeoServer

**Comment by andreweijmer** [comment]
Klopt, ook de nieuw toegevoegde sld's worden niet naar geoserver doorgezet

**Comment by copierrj** [comment]
Er zijn hier drie dingen die een rol spelen:
- Een laag heeft stijlen. Bij het opvragen van een laag kan een gebruiker de gewenste stijl kiezen. De eerste stijl die wordt geconfigureerd is de zogeheten standaard stijl. Dit houd in dat deze stijl gebruikt wordt bij een 'GetMap' request waarbij de 'style' parameter niet is ingevuld. Om dit in de interface duidelijk te maken heb ik deze stijl een afwijkende kleur gegeven.
  ![image](https://cloud.githubusercontent.com/assets/2194475/7515350/76c97e86-f4c6-11e4-9494-039feaba68f7.png)<br>
  Deze informatie bleek echter niet correct te worden doorgezet naar GeoServer. Dit is inmiddels verholpen.
- Als een laag in een groep wordt opgenomen bestaat de mogelijkheid om voor deze laag een afwijkende stijl te kiezen. Dit heeft geen gevolgen voor het opvragen van die individuele laag. De stijl die hier kan worden opgegeven is de stijl die wordt gebruikt als de gebruiker de groepslaag opvraagt. Als hier niets geconfigureerd is wordt in dit geval de standaardstijl van de laag gebruikt.
- Services en groepen hebben de nodige gemeenschappelijke eigenschappen. De verschillende invulvelden in de formulieren gebruiken hierdoor dezelfde softwarecomponenten. Het toevoegen van de stijlkeuze voor lagen in groepen had hierdoor onbedoeld tot gevolg dat deze keuzemogelijkheid ook in het service formulier beschikbaar kwam. Met deze informatie kan in deze context echter niets worden gedaan. Deze keuzemogelijkheid is daarom uit het serviceformulier verwijderd en wordt nu nog enkel in het groepformulier getoond.

**Comment by andreweijmer** [comment]
werkt correct
