### ISSUE TITLE
Inlezen zware bronbestanden lukt niet

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#50]
het lijkt erop dat het importeren van zware bronbestanden mislukt. De import van het postcodebestand heeft zowat 2 uur geduurd en geeft dan een foutmelding.

**Comment by copierrj** [comment]
Om dit probleem goed te kunnen analyseren is het belangrijk dat we eerst de bandbreedte tussen onze service en het provider component bij de provincie meten.

**Comment by andreweijmer** [comment]
Heb het postcode-6 bestand geïmporteerd. maakt echter geen laag aan in geoserver.

**Comment by andreweijmer** [comment]
Blijft hetzelfde. Hij leest het postcode bestand wel netjes in maar maakt geen laag in geoserver aan.

**Comment by andreweijmer** [comment]
Zware (vector) bronbestanden worden nu wel ingelezen.  Bij Raster is nog probleem geconstateerd (zie nieuw aangemaakt issue)
