### ISSUE TITLE
Vraag Foutmeldingen

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#51]
Ik heb net getracht het postcodebestand te importeren. Daarbij trad een foutmelding op. Dan zou deze foutmelding toch ook onder logboek/foutmeldingen getoond moeten worden?

**Comment by HermanAssink** [comment]
Vermoedelijk was de oorzaak het tijdelijk wegvallen van de verbinding. Zo'n probleem wordt op dit moment niet gelogd zodat het zichtbaar is in de beheerinterface. Zie ook mijn opmerking bij #52

**Comment by andreweijmer** [comment]
Ok
