### ISSUE TITLE
Datasets/status: foutmeldingen worden niet weergegeven

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#52]
Er is een fout bij het importeren opgetreden voor het postcodebestand. Als ik dan in het gedeelte status op "fouten bij importeren klik" zou ik de foutmelding van de postcodegebieden moeten zien.

**Comment by HermanAssink** [comment]
Fouten bij import betreffen bugs, waar wij als IDgis bijna altijd bij ingeschakeld moeten worden. Voor fouten die optreden aan de kant provider moeten we op dit moment de technische log van de provider bekijken. Dat kan nu alleen via Reinder / systeembeheer Overijssel. Bij fouten aan de kant van de harvester&importer kunnen we de oorzaak analyseren mbv de log op ons systeem. Betere weergave van bugs en systeemfouten in de beheerapplicatie zouden we als wens kunnen noteren.

**Comment by andreweijmer** [comment]
Ok
