### ISSUE TITLE
Beveiliging: vraag

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#55]
Hoe kan ik het beste de toegang tot de beveiligde services testen. Als ik de onderstaande url's gebruik krijg ik alle info te zien op een omgeving buiten het provinciehuis.

Beveiligde service eigendomsgrens

getcapabilities
http://acc-staging-services.geodataoverijssel.nl/geoserver/Beveiligd/wms?service=WMS&request=GetCapabilities&version=1.3.0

getmap
http://acc-staging-services.geodataoverijssel.nl/geoserver/Beveiligd/wms?service=WMS&version=1.1.0&request=GetMap&layers=Beveiligd:Eigendomsgrens_van_de_provinciale_infrastructuur&styles=&bbox=175000,450000,275000,550000&width=512&height=512&srs=EPSG:28992&format=application/openlayers

Getlegend
http://acc-staging-services.geodataoverijssel.nl/geoserver/Beveiligd/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=Eigendomsgrens_van_de_provinciale_infrastructuur

**Comment by HermanAssink** [comment]
De staging services zijn niet beveiligd, wel de beveiligde en gegarandeerde omgeving. De url's daarvan zijn:

gegarandeerd: http://acc-guaranteed-services.geodataoverijssel.nl/geoserver/
beveiligd: http://acc-secure-services.geodataoverijssel.nl/geoserver/

Deze omgevingen zouden alleen toegankelijk moeten zijn met de IP-adressen van Overijssel.

**Comment by andreweijmer** [comment]
Beveiliging werkt correct. Geeft intern de getcapabilities en extern een 403 melding
