### ISSUE TITLE
Tiling wordt niet uitgevoerd

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geo-publisher-test#56]
De tiling van de groeplayer is door André Weijmer op acc aangevraagd, maar niet uitgevoerd. Ook geprobeerd de laag “gemeentegrenzen Overijssel” te tilen. Dit lukt ook niet. Het lijkt erop dat de actie in de wachtrij geplaatst wordt.

**Comment by copierrj** [comment]
Het systeem bleek bij een crash van de provisioning alle service informatie (= urls naar GeoServer installaties) kwijt te raken. Hierdoor werkte de provisioning vervolgens niet meer. Dit probleem is verholpen. Het gemelde probleem zou (o.a.) hierdoor veroorzaakt kunnen worden.

**Comment by andreweijmer** [comment]
Tilingfunctionaliteit werkt nu correct. Ik heb echter een vraag. 

Als de dataset inhoudelijke aanpassingen heeft ondergaan, dan moet de laag opnieuw getiled worden. Geschiedt dat dan door de tiling te verwijderen en daarna opnieuw te tilen? Ik zie namelijk geen knop "opnieuw tilen"
