### ISSUE TITLE
harvester en script voor splitsing raster/vector metadata moeten qua tijdstip afgestemd worden.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geo-publisher-test#57]
Het script bij Overijssel dat de metadata splitst in een map met vector en een map met rasterdata maakt bij een run betreffende mappen eerst leeg en vult deze dan opnieuw. Hierdoor bestaat het risico dat de harvester bij een harvest actie lege mappen aantreft, wat onwenselijk is. Het tijdstip van de metadata update bij Overijssel en de harvest actie moeten worden afgestemd zodat bovenstaande situatie niet kan optreden.

**Comment by HermanAssink** [comment]
Verzoek André: Graag willen wij dat het harvesten 1x per uur (op het hele uur) plaats vindt. Nu wordt de harvest elk kwartier uitgevoerd waardoor het lijkt of er continue geharvest wordt. Reinder zal zijn script dan aanpassen zodat die op elk half uur draait. Graag Reinder even berichten wanneer dit ingesteld is.

**Comment by HermanAssink** [comment]
@ Reinder Hoekstra: Het is gewenst het script voor splitsing van de metadata min of meer transactioneel te maken. Kun je niet de output van het script in een nieuwe map zetten en als dat klaar is de oude map verwijderen en de nieuwe hernoemen? Die laatste twee handelingen kunnen als één file system transactie.

**Comment by HermanAssink** [comment]
@andreweijmer Wil jij bovenstaand voorstel communiceren met Reinder? Of beter, Kan Reinder ook lid worden van GitHUb?

**Comment by copierrj** [comment]
cc: @reinderhoekstra

**Comment by reinderhoekstra** [comment]
1. Ik weet niet precies hoe "Die laatste twee handelingen kunnen als één file system transactie" in een windows-os uitgevoerd moet worden. Is er niet altijd nog een moment waarop de te harvesten map niet beschikbaar is? Misschien kan IDGIS hierover mij het eea uitleggen?
2. Mijn script is in een paar seconden klaar. Dit wetende is mijn tegenvoorstel:
   a. vasthouden aan het afgestemde schedulen van de harvester en het splitsing-script
   b. optioneel: de harverster robuuster maken door in te bouwen dat - als het voorkomt dat de te harvesten map leeg is door het splitsing-script - de harvester 1 minuut later nog eens te laten harvesten om te constateren dat de map weer gevuld is door het splitsing-script.

**Comment by copierrj** [comment]
Er zijn twee wijzigingen doorgevoerd in de programmatuur:
- Het harvesten vindt nu ieder heel uur plaats (ipv iedere 15 minuten)
- Voordat de provider metadata gaat verwerken wordt er nu gecontroleerd of de metadata map aanwezig is. Is dit niet het geval dan wordt het na 10 seconden opnieuw geprobeerd. Dit herhaald zich maximaal 5 keer. Lukt het dan nog steeds niet dan wordt het harvesten afgebroken.

Hiermee zou het mogelijk moeten zijn om het geheel robuust te krijgen. Het script zou hierbij de volgende werkwijze kunnen hanteren:
- maak een nieuwe map aan onder een andere naam.
- vul deze nieuwe map met metadata bestanden.
- verwijder de oude map.
- hernoem de nieuwe map naar de oude naam.

**Comment by andreweijmer** [comment]
Werkt volgens mij correct. kan volgens mij afgesloten worden
