### ISSUE TITLE
Databeheer / brongegevens / benaming bron

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#6]
Brongegevens moeten hiërarchisch boven datasets geplaatst worden.

**Comment by HermanAssink** [comment]
Wordt bedoeld dat het item Brongegevens boven Datasets moet staan in het menu?

**Comment by andreweijmer** [comment]
Ja, brongegevens zijn de metagegevens. Een dataset van een van de brongegevens staat in de stage omgeving. Het is dus veel logischer om brongegevens boven de dataset te plaatsen in het menu.

**Comment by HermanAssink** [comment]
OK, gaan we doen.

**Comment by andreweijmer** [comment]
is nu correct
