### ISSUE TITLE
Viewer om te bladeren door gepubliceerde WMS lagen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geo-publisher-test#63]
Basale GIS-viewer die de mogelijkheid biedt om te bladeren door de WMS lagen. Viewer wordt automatisch aangepast bij het (opnieuw) publiceren van een service

**Comment by copierrj** [comment]
Opgeleverd als onderdeel van versie 1.1.6: https://github.com/IDgis/geo-publisher/pull/712
