### ISSUE TITLE
Inlezen rasterbestand AHN25 lukt niet

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#68]
De rasterdataset AHN25 wordt niet geimporteerd. Kort heeft hij onder systeemtaken op ingepland gestaan. maar vervolgens is hij daar verdwenen en blijft de status van de dataset nog op "niet geimporteerd" staan.

**Comment by andreweijmer** [comment]
Inlezen AHN25 lukt nu wel. maar toont niet in preview. Op het dashboard bij systeemtaken wordt aangegeven : Bezig met service (staging).

**Comment by copierrj** [comment]
Er blijken hier hier twee dingen fout te gaan:
- de gebruikte stijl is niet correct (overlap in bandwaarden) waardoor de laag niet werkt.
- het doorvoeren van wijzigingen op een bestaande laag werkt niet correct wat tot gevolg heeft dat de tekst 'Bezig met service (staging)' in het dashboard blijft staan. #72

**Comment by copierrj** [comment]
@andreweijmer: heeft deze AHN stijl bij jullie in het verleden gewerkt?

**Comment by andreweijmer** [comment]
Deze stijl is opnieuw gemaakt door geocat Bridge in ArcGIS
