### ISSUE TITLE
functionaliteit werkt niet meer na enige tijd

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#69]
Ik heb geconstateerd dat als ik ongeveer een kwartier niets doe in de pubomgeving en ik dan bepaalde functionaliteit gebruik (bijv. op dashboard/alle systeemtaken) deze niet reageert. Na uitgelogd te hebben en opnieuw in te loggen werkt deze wel weer.

Als dit te maken heeft met een bepaalde tijdsinstelling dan zou het systeem toch automatisch moeten uitloggen of in ieder geval een melding af moeten geven.

**Comment by copierrj** [comment]
Het lukt mij helaas niet om het probleem te reproduceren. Ik heb het dashboard 20 minuten open laten gaan en toen op "Bekijk alle systeemtaken" geklikt. Dit werkte correct.

**Comment by andreweijmer** [comment]
OK
