### ISSUE TITLE
Opnieuw tilen na aanpassingen

### ISSUE THREAD

**Issue by copierrj** [IDgis/geo-publisher-test#70]
Als de dataset inhoudelijke aanpassingen heeft ondergaan, dan moet de laag opnieuw getiled worden. Geschiedt dat dan door de tiling te verwijderen en daarna opnieuw te tilen? Ik zie namelijk geen knop "opnieuw tilen"

(opmerking van @andreweijmer in: #56)

**Comment by copierrj** [comment]
Zojuist heb ik het volgende gedrag geïmplementeerd:
- Voor nieuwe tiling lagen worden automatisch seed acties gestart
- Na het herimporteren van een dataset worden er service jobs aangemaakt voor alle services die een laag bevatten obv het desbetreffende dataset. Bij het uitvoeren van deze service jobs zal worden geconstateerd dat de tiled layer ouder is dan de laatste dataset import en zal een reseed actie gestart worden.
- Bij (re)seed actie geld op dit moment altijd: zoom start = 0, zoom stop = 9

Openstaand punt: ingeplande overbodige (re)seed acties annuleren #73

**Comment by andreweijmer** [comment]
Werkt.
