### ISSUE TITLE
structuurwijziging wordt niet goed doorgevoerd

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#74]
Na het doorzetten van een structuurwijziging worden de nieuwe toegevoegde kolomnamen niet getoond tijdens een identify. Ook in de WFS is de wijziging niet terug te vinden

http://acc-staging-services.geodataoverijssel.nl/geoserver/OV_B6/wms?service=WMS&version=1.1.0&request=GetMap&layers=OV_B6:Aardgastransportleidingen&styles=&bbox=175000,450000,275000,550000&width=512&height=512&srs=EPSG:28992&format=application/openlayers

De kolommen "test" en "Test2" zouden getoond moeten worden.

**Comment by copierrj** [comment]
Als er in het brondataset nieuwe kolommen zijn bijgekomen dan worden deze kolommen na het accepteren van de structuurwijziging niet automatisch geïmporteerd.  Dit komt omdat bij het maken van een dataset (obv een brondataset) een kolomselectie gemaakt is. Nieuwe kolommen worden niet automatisch toegevoegd aan deze selectie. Om nieuwe kolommen toe te voegen aan een dataset dient de kolomselectie met de hand te worden gewijzigd:

![image](https://cloud.githubusercontent.com/assets/2194475/7957737/f7cc8b94-09e9-11e5-83b1-b33aec90f686.png)

Nadat de gegevens opnieuw zijn ingelezen (dit gebeurd automatisch) worden de services (eveneens automatisch) aangepast aan de nieuwe situatie.

**Comment by andreweijmer** [comment]
Ok. is duidelijk
