### ISSUE TITLE
Publiceren van services gaat niet goed

### ISSUE THREAD

**Issue by copierrj** [IDgis/geo-publisher-test#75]
(Melding van @andreweijmer)

Het aantal lagen in de publicatie is veel lager dan het zou moeten zijn.

**Comment by copierrj** [comment]
Directe oorzaak: service jobs konden niet worden uitgevoerd doordat de database connecties op waren. Zie: IDgis/geo-publisher#703. Na herstart van de service werden de service jobs correct uitgevoerd.

**Comment by copierrj** [comment]
Ter controle uitgevoerde sql script om het correcte aantal lagen te bepalen:

``` sql
with recursive layers as (
    select
        service_id,
        json_array_elements(content::json -> 'layers') -> 'layer' layer, 
        0 depth
    from publisher.published_service
    union all
    select
        service_id, 
        json_array_elements(layer -> 'layers') -> 'layer' layer,
        depth + 1 depth
    from layers
)
select e.identification, count(*) from layers l
join publisher.published_service_environment pse on pse.service_id = l.service_id
join publisher.environment e on e.id = pse.environment_id
group by 1
```

**Comment by copierrj** [comment]
Onderliggende oorzaak gevonden in GeoServer: de individuele data stores in de verschillende workspaces maken ieder hun eigen individuele database connectie pool.

**Comment by copierrj** [comment]
Oplossing: GeoServer wordt vanaf de komende release zo ingericht dat er gebruik gemaakt wordt van JNDI zoals beschreven in de GeoServer documentatie: http://docs.geoserver.org/2.7.1/user/tutorials/tomcat-jndi/tomcat-jndi.html

**Comment by copierrj** [comment]
Opgelost met: https://github.com/IDgis/geo-publisher/pull/704

**Comment by andreweijmer** [comment]
Beste Reijer,

Korte vraag. Kan ik al weer testen in de acceptatie omgeving of moet ik nog even wachten?

André Weijmer

Van: Reijer Copier [mailto:notifications@github.com]
Verzonden: vrijdag 13 november 2015 14:21
Aan: IDgis/geo-publisher-test
CC: Weijmer, AM (Andre)
Onderwerp: Re: [geo-publisher-test] Publiceren van services gaat niet goed (#75)

Closed #75https://github.com/IDgis/geo-publisher-test/issues/75.

—
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geo-publisher-test/issues/75#event-463582840.

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---
