### ISSUE TITLE
Kolom GlobalId gaat niet mee

### ISSUE THREAD

**Issue by PeterAukeNicolaij** [IDgis/geo-publisher-test#76]
Kan het zijn dat bij datasets met een GlobalId (bijv. voor INSPIRE) deze kolom niet overkomt naar jullie database?

**Comment by HermanAssink** [comment]
Hallo Peter Auke, Hebben deze GlobalId/GUID kolommen een speciaal datatype in Oracle? Zo ja, dan is dat waarschijnlijk de verklaring. Heb je één of meer voorbeelden van tabellen met zo'n kolom waarbij zich het probleem voordoet? Groeten, Herman

**Comment by PeterAukeNicolaij** [comment]
Ja het gaat om de INSPIRE datasets waarbij deze kolom niet mag ontbreken.
Voorbeelden zijn oa.: zeer kwetsbare gebieden (wav_polygon), Nationale Landschappen en de EHS. Deze bevinden zich allen in de B4.B46 service. In onze GeoServer omgeving zie ik deze kolom wel terug. Ik weet niet of het een speciaal datatype is maar vermoed het wel.

**Comment by HermanAssink** [comment]
Klopt, deze kolommen hebben een afwijkend datatype, namelijk CHAR(38). Reijer zoekt het uit hoe snel dit te fixen is.

**Comment by copierrj** [comment]
De volgende versie (1.1.8) van de provider biedt ondersteuning voor CHAR en NCHAR. Nadat deze is geïnstalleerd zullen kolommen van deze datatypen in de admin verschijnen als nieuwe kolom (= structuurwijziging).
