### ISSUE TITLE
Servicebeheer / lagen /knop maak nieuwe laag met dataset in onderkast?

### ISSUE THREAD

**Issue by andreweijmer** [IDgis/geo-publisher-test#8]
Een nieuwe laag waarin hoofdletters voorkomen worden volgens ons in geoserver omgezet naar onderkast. Is dit waar?

**Comment by HermanAssink** [comment]
Nee, heb je een geval waarbij dat is waargenomen?
Tabelnamen werden wel omgezet naar onderkast, maar tabelnamen worden onzichtbaar in de volgende versie.

**Comment by andreweijmer** [comment]
Issue kan gesloten worden. kan het op dit moment niet meer reproduceren. Misschien bij een nieuwe test.
