### ISSUE TITLE
De GetCapabilities van de WFS bevat een link naar de Metadata zoals beschikbaar in de GeoPublisher

### ISSUE THREAD

**Issue by kraaka** [IDgis/geo-publisher-test#83]
- URL is vindbaar in de GetCapabilities  en werkt

**Comment by copierrj** [comment]
bevinding: geoserver wfs capabilities bevat in het geheel geen metadata links.

**Comment by copierrj** [comment]
wfs feature types (b)lijken geen metadata url te hebben (zie bijvoorbeeld: http://services.inspire-provincies.nl/ProtectedSites/services?request=GetCapabilities&service=WFS)
