### ISSUE TITLE
verwijderde brongegevens uit lijst verwijderen

### ISSUE THREAD

**Issue by CoraPU** [IDgis/geo-publisher-test#90]
Op welk moment verwijderd de brongegeven uit de lijst als de gekoppelde datasets verwijderd zijn en de notificaties afgevlagd.  Een aantal zijn al een aantal weken geleden verwijderd in de bron en afgevlagd
 
![image](https://user-images.githubusercontent.com/30464824/31649839-11e8c0ac-b315-11e7-90af-946407ba1b57.png)

**Comment by SandroNeumann** [comment]
Komt omdat er nog import jobs zijn die in de verwijder transactie niet worden verwijderd. Waardoor een fout afgaat en de hele transactie faalt. Deze bug zijn we recentelijk ook tegen gekomen en hebben het inmiddels gefixt. Komt mee met de volgende oplevering.
